export const skillData =[
    {
        srcc:"../images/cpp.png",
        name:"C++"
    },
    {
        srcc:"../images/ps.png",
        name:"Data Structures and Algorithms"
    },
    {
        srcc:"../images/db.png",
        name:"SQL"
    },
    {
        srcc:"../images/mongodb2.png",
        name:"MongoDB"
    },
    {
        srcc:"../images/express.png",
        name:"Express"
    },
    {
        srcc:"../images/react.png",
        name:"React"
    },
    {
        srcc:"../images/nodejs.png",
        name:"NodeJS"   
    },
    {
        srcc:"../images/html.png",
        name:"HTML"
    },
    {
        srcc:"../images/css.png",
        name:"CSS"
    },
    {
        srcc:"../images/js.png",
        name:"JavaScript"    
    },
    {
        srcc:"../images/git.png",
        name:"Git"
    },
    {
        srcc:"../images/github.png",
        name:"GitHub"
    },
    {
        srcc:"../images/bs.png",
        name:"Bootstrap"
    },
    {
        srcc:"../images/mui.png",
        name:"Material Ui"
    }
  ];
  